@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 07 16:28:05 +0100 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim cfg_tb_rete4_4_behav -key {Behavioral:sim_1:Functional:cfg_tb_rete4_4} -tclbatch cfg_tb_rete4_4.tcl -view C:/Users/riovi/Dropbox/LABORATORIO/Elaborato_ASDI/OMEGANET NICOLA/11_SWITCH_MULTISTADIO/cfg_tb_rete4_4_behav.wcfg -log simulate.log"
call xsim  cfg_tb_rete4_4_behav -key {Behavioral:sim_1:Functional:cfg_tb_rete4_4} -tclbatch cfg_tb_rete4_4.tcl -view C:/Users/riovi/Dropbox/LABORATORIO/Elaborato_ASDI/OMEGANET NICOLA/11_SWITCH_MULTISTADIO/cfg_tb_rete4_4_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
